name: Deploy to Production

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd apps
            cd covid19-api
            git pull
            composer i
            php artisan migrate --force
            php artisan optimize
            npm ci
            npm run prod
